version: "3.8"

services:
  postgres:
    restart: unless-stopped
    image: postgres:14
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - "9920:5432"
    networks:
      - test

networks:
  test:
    driver: bridge
